name: flutter_app
description: "A new Flutter project."
publish_to: 'none'  # Bu uygulama pub.dev'de yayınlanmayacak
version: 0.1.0      # Uygulama versiyonu

environment:
  sdk: ^3.5.4      # Flutter SDK versiyonu

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8       
  flutter_secure_storage: ^9.2.2 
  go_router: ^14.6.1            
  shared_preferences: ^2.3.3     
  dotlottie_loader: ^0.0.4
  lottie: ^3.1.3
  provider: ^6.1.2
  image_picker: ^0.8.7+4
  file_picker: ^8.1.7
  path_provider: ^2.1.2 
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0         # Kod kalitesi kontrolleri için

flutter:
  uses-material-design: true    # Material Design widget'larını kullanmak için
  assets:                       # Projedeki dosya kaynakları
    - assets/images/            # Görseller için
    - assets/icons/             # İkonlar için
    - assets/motions/           # Animasyon dosyaları için
    - assets/data/news.json     # Haberleri buraya kaydetmek için